print("0.Quitterle programme")
print( "1.Afficherlescoureurs")
print("2.Afficherleclassementprovisoire")
print("3.Enregistrerunearrivée")
print("4.Enregistrerunabandon")
print("5.Enregistrerunedisqualification")
print("6.Enregistrerletemps d’arrivée d’un coureur")
print("7.Obtenirletemps d’un coureur")
print("8.Obtenir l’écartdetemps entre deux coureursdonnés")